package shared

const (
	ServiceOutboundAppNet        = "appnet"
	ServiceOutboundAtom1         = "atom1.0"
	ServiceOutboundBlogger       = "blogger"
	ServiceOutboundBuddycloud    = "buddycloud"
	ServiceOutboundDiaspora      = "diaspora"
	ServiceOutboundDreamwidth    = "dreamwidth"
	ServiceOutboundDrupal        = "drupal"
	ServiceOutboundFacebook      = "facebook"
	ServiceOutboundFriendica     = "friendica"
	ServiceOutboundGNUSocial     = "gnusocial"
	ServiceOutboundGoogle        = "google"
	ServiceOutboundInsaneJournal = "insanejournal"
	ServiceOutboundLibertree     = "libertree"
	ServiceOutboundLinkedIn      = "linkedin"
	ServiceOutboundLiveJournal   = "livejournal"
	ServiceOutboundMediaGoblin   = "mediagoblin"
	ServiceOutboundMySpace       = "myspace"
	ServiceOutboundPinterest     = "pinterest"
	ServiceOutboundPnut          = "pnut"
	ServiceOutboundPosterous     = "posterous"
	ServiceOutboundPumpIO        = "pumpio"
	ServiceOutboundRedMatrix     = "redmatrix"
	ServiceOutboundRSS2          = "rss2.0"
	ServiceOutboundSMTP          = "smtp"
	ServiceOutboundTent          = "tent"
	ServiceOutboundTumblr        = "tumblr"
	ServiceOutboundTwitter       = "twitter"
	ServiceOutboundWordPress     = "wordpress"
	ServiceOutboundXMPP          = "xmpp"
	ServiceOutboundZot           = "zot"
)
